Fixed exception in tests with PK-prefixed fields
This exception was caused by the code in `UploadToUtils.rename_files_of_created_instances()` trying to rename a file to have the same filename as an
existing file that was left undeleted from a previously run test case.
Example error message:
```
FileExistsError: [WinError 183] Cannot create a file when that file already exists: '[file path]\--replacedByPK-1f941ab7-KPyBdecalper--_img.jpg' -> '[file path]\1_img.jpg'
```

The exception seems to only happen on (some?) Windows systems, as the tests on GitHub did not fail (which run on an Ubuntu machine),
and neither did they fail on the Windows 10 machine that I originally wrote the code for `CleanUpTempFilesTestMixin` and
`UploadToUtils.get_pk_prefixed_filename_func()` (I'm currently developing on an older Windows 11 machine).