Fixed AttributeError when undefined request object
I *think* that when a certain unrelated error occurs, it causes the `request` template variable to be undefined, but I don't remember exactly..
In any case, this caused the variable to instead be an empty string (standard Django template behavior), which again caused one of the following
errors when the current template used any of the template tags in `uri_tags.py`:
`AttributeError: 'str' object has no attribute 'build_absolute_uri'`
or:
`AttributeError: 'str' object has no attribute 'path'`