Replaced >= with == in requirements.txt
This was mainly for preventing the CI server (GitHub Actions) from testing with too new versions of the required packages,
which caused the testing to fail.

In the case that prompted this change, it was `django-hosts` that hadn't yet added support for the newest version
of Django (which was released yesterday), which caused the following error:
`ImportError: cannot import name 'ugettext_lazy' from 'django.utils.translation'`